"""
List of major Indian cities with railway service
"""

INDIAN_RAILWAY_CITIES = [
    "Agra",
    "Ahmedabad",
    "Amritsar",
    "Bengaluru",
    "Bhopal",
    "Bhubaneswar",
    "Chennai",
    "Coimbatore",
    "Delhi",
    "Ernakulam",
    "Guwahati",
    "Gwalior",
    "Hyderabad",
    "Indore",
    "Jaipur",
    "Jalandhar",
    "Jammu",
    "Kanpur",
    "Kochi",
    "Kolkata",
    "Lucknow",
    "Ludhiana",
    "Madurai",
    "Mangalore",
    "Mumbai",
    "Mysore",
    "Nagpur",
    "Navi Mumbai",
    "New Delhi",
    "Patna",
    "Pune",
    "Raipur",
    "Rajkot",
    "Ranchi",
    "Secunderabad",
    "Surat",
    "Thiruvananthapuram",
    "Thrissur",
    "Tiruchirappalli",
    "Tirupati",
    "Vadodara",
    "Varanasi",
    "Vijayawada",
    "Visakhapatnam"
]